version: '3'
services:
  node-app:
    image: kooroushpsnd/blog-back
    env_file:
      - ./.env.example
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:/data/db

  vue-js:
    image: kooroushpsnd/blog-front
    ports:
      - "8080:8080"
    
volumes:
  mongo-db: